type = "webpack"
webpack_config = "webpack.config.js"
zone_id = "d590ecbf2de803f296e6ad0b9b9c9f3d"
compatibility_date = "2021-11-25"

[site]
bucket = "./app/public"
entry-point = "."

[env.dev]
name = "sandboxbio-dev"
routes = ["dev.sandbox.bio/*"]
vars = { ENVIRONMENT = "dev" }

[env.stg]
name = "sandboxbio-stg"
routes = ["stg.sandbox.bio/*"]
vars = { ENVIRONMENT = "stg" }

[env.prd]
name = "sandboxbio"
routes = ["sandbox.bio/*", "prd.sandbox.bio/*"]
vars = { ENVIRONMENT = "prd" }
