type = "webpack"
webpack_config = "webpack.config.js"
zone_id = "d590ecbf2de803f296e6ad0b9b9c9f3d"

[site]
bucket = "./app/public"
entry-point = "."

[env.stg]
name = "sandboxbio-stg"
route = "stg.sandbox.bio/*"

[env.prd]
name = "sandboxbio"
route = "prd.sandbox.bio/*"
