type = "webpack"
webpack_config = "webpack.config.js"
zone_id = "d590ecbf2de803f296e6ad0b9b9c9f3d"

[site]
bucket = "./app/public"
entry-point = "."

[env.dev]
name = "sandboxbio-dev"
routes = ["dev.sandbox.bio/*"]

[env.stg]
name = "sandboxbio-stg"
routes = ["stg.sandbox.bio/*"]

[env.prd]
name = "sandboxbio"
routes = ["prd.sandbox.bio/*"]  # TODO: add sandbox.bio/*
