type = "webpack"
webpack_config = "webpack.config.js"
zone_id = "d590ecbf2de803f296e6ad0b9b9c9f3d"

[site]
bucket = "./app/public"
entry-point = "."

[env.stg]
name = "sandboxbio-stg"
route = "stg.sandbox.bio/*"

# kv_namespaces = [
#    { binding = "LOGS", id = "dd7c61572f59436796f1404eff1eec3a" }
# ]
