# Deploy to sandbox.bio manually

name: prd.sandbox.bio

on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy sandbox.bio
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Deploy
        run: |
          npm i -g @cloudflare/wrangler
          npm run deploy-prd
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
