# Deploy to dev.sandbox.bio whenever push to dev branch

name: dev.sandbox.bio

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy dev.sandbox.bio
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          npm i -g @cloudflare/wrangler
          npm run deploy-dev
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
