# Deploy to stg.sandbox.bio whenever push to main branch

name: Deploy stg.sandbox.bio

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy stg.sandbox.bio
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          npm i -g @cloudflare/wrangler
          npm run deploy-stg
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
