# FIXME: Write steps that do the deploy
name: Deploy sandbox.bio

on:
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy sandbox.bio (${{ github.ref }})
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
