# Run app tests whenever push to dev branch

name: Tests

on:
  push:
    branches: [ dev ]
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build
        run: cd app && npm install && npm run build

      - name: Run tests
        run: cd app && npm run dev & npm run test
