name: Tests

on:
  push:
    branches: [v2]

env:
  PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
  PUBLIC_SUPABASE_API_KEY: ${{ secrets.PUBLIC_SUPABASE_API_KEY }}
  SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up playwright
        run: npm install && npm run build && npx playwright install chromium

      - name: Run tests
        run: npm run test
