# Run app tests whenever push to dev branch

name: Tests

on:
  push:
    branches: [ dev ]
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build
        run: cd app && npm install && npm run build

      - name: Launch dev server
        uses: cypress-io/github-action@v5
        with:
          start: cd app && npm start
          wait-on: 'http://localhost:1111'

      - name: Run tests
        run: cd app && npm run test
