name: Tests

on:
  push:
    branches: [v2]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up playwright
        run: npm install && npx playwright install chromium

      - name: Run tests
        run: npm run test
