name: Sandbox.bio Tests

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'workers/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build
        run: npm install && npm run build && npm run dev &

      - name: Run tests
        run: npm run test

      - name: Deploy to Cloudflare Pages DEV
        run: curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{ secrets.CF_PAGES_HOOK_TOKEN_DEV }}"
